### ISSUE TITLE
Direct download throws up dependencies against Pharo 7 64bit stable

### ISSUE THREAD

**Issue by Bazmundi** [OpenPonk/openponk#10]
What is the starting Pharo image works with the direct download?

I tried the following.
==============================================================

Running windows 10.

Installed Pharo from: https://files.pharo.org/pharo-launcher/windows to get pharo-launcher-1.9.2

Starting with:
Pharo 7.0.4
Build information: Pharo-7.0.4+build.169.sha.a2a2b23d681754955d27b7c5a47ed1e9f87ef7b8 (64 Bit)

Then loaded metacello with:

```
Iceberg enableMetacelloIntegration: false.

Metacello new
    baseline: 'Metacello';
    repository: 'github://metacello/metacello:pharo-6.1_dev/repository';
    onConflict: [ :ex | ex allow ];
    load.

```
I did that because trying to run Metacello to install openponk from the playground of the virgin pharo install just crashed out of pharo.  Not even sure why I tried the lines above, other than I assumed Metacello was not installed in virgin pharo install.  It appeared to fix the crash,.

Then tried to direct install openponk with:

```
Metacello new
     baseline: 'OpenPonk';
     repository: 'github://openponk/openponk/repository';
     load: 'complete'

```
I get a message:
```
This package depends on the following classes:
  Nautilus
You must resolve these dependencies before you will be able to load these definitions: 
  Nautilus>>#showMethod:

```
I hit "Proceed" to ignore the report.

It proceeds up to the following report:

```
The method Base64MimeConverter class>>#mimeDecodeToBytes: called from TRPharoPlatform>>#mimeDecodeToBytes: has been deprecated.
Please use #base64Decoded now. See issue #21937

Select Proceed to continue, or close this window to cancel the operation.
```

Hitting "Proceed" just gets it stuck in a loop that keeps then reporting the same warning.

Hitting "Debug" reports:

```
deprecated: anExplanationString
	"Warn that the sending method has been deprecated"
	
	Deprecation new
		context: thisContext sender;
		explanation: anExplanationString;
		signal
```

Hitting "Proceed" from the debug window then abort stops the install.

Is there a fix please?

**Comment by Bazmundi** [comment]
I tried Pharo 6.0.  Came up with one warning during load of OpenPonk.   Seemed to load okay.  However, the first drawing menu just raised exceptions and when cleared the editor window was only partially drawn.  The second and third drawing menus came up with pallets but nothing was drawing on the canvas.

**Comment by Bazmundi** [comment]
Yep. Tried pharo 6.1 with same outcome as 6.0.

**Comment by Bazmundi** [comment]
Same problems on my Debian 10 laptop.

**Comment by peteruhnak** [comment]
Unfortunately Pharo 7/8 is not supported (this should be addressed next year).

As for the complete build (`... load: 'complete'`), this tries to download all known plugins for OpenPonk, which are at this point in time not compatible.

Trying to install the plugins directly may yield a better result, e.g. installing only https://github.com/OpenPonk/class-editor

However as I've responded in the other thread, the download links should now work once again.

**Comment by Bazmundi** [comment]
Peter. Thanks for fixing the links, I will start with that.

**Comment by JanBliznicenko** [comment]
Hello, we started working on updating for Pharo 7 and 8. At this moment, master branches of OpenPonk itself, class-editor, borm-editor, fsm-editor and petrinets can be loaded and opened on Pharo 7 and 8. It means that even `load: 'complete'` should work. 
However, making it load does not mean it works yet :) Many essential things do not work properly yet, including canvas refreshing, adding associations (on Pharo 8) as well as our builds on openponk.org.
I believe all of that will be fixed soon™ :)
