### ISSUE TITLE
It just eats all memory and freezes (CTU class)

### ISSUE THREAD

**Issue by MarekSuchanek** [OpenPonk/openponk#102]
CTU classroom T9:351, Windows

Steps:

1. Download nightly build (as latest 3.0.4 is very old)
2. Unzip it (still in Downloads dir)
3. Run .bat
4. After few moments it starts but also starts to gradually consuming memory (RAM).
5. Cannot open UML CD editor (or others)...
6. Resize of window helps with freeze sometimes, but sometimes it does not even re-render (black stripes).

In Task Manager, you see just growing number of RAM consumed (the computer has 32 GB).

![image](https://github.com/OpenPonk/openponk/assets/9638527/8d1dc3a0-087b-4e0e-bd8e-51e292e018a0)
![image](https://github.com/OpenPonk/openponk/assets/9638527/17de51d4-b85b-4e32-8255-57946e96b64e)

(I tried to let it run for few more minutes... then got scared of consuming all of memory, so killed it.)

![image](https://github.com/OpenPonk/openponk/assets/9638527/4cb253a5-01d0-4c52-b19f-7e0d51b7d192)

**Comment by JanBliznicenko** [comment]
It seems like the CI glitched - current builds look ok without any relevant changes from my side

**Comment by MarekSuchanek** [comment]
> It seems like the CI glitched - current builds look ok without any relevant changes from my side

![image](https://github.com/OpenPonk/openponk/assets/9638527/664b9b16-41f1-4eb2-a120-30ef516f0ac5)
