### ISSUE TITLE
Leftovers after deleting asociations

### ISSUE THREAD

**Issue by BoomXfight** [OpenPonk/openponk#103]
I created 2 classes and connected them with the association. Afterward, I deleted the association using the delete button. The line disappeared, however, the multiplicity and names of the classes remained on the canvas without ability to delete them.

**Comment by JanBliznicenko** [comment]
Hello, thank you for letting us know. Does it happen in numbered version (3.something) or nightly build?

**Comment by BoomXfight** [comment]
Hello, no problem. It happens in nightly build.

**Comment by JanBliznicenko** [comment]
It should be fixed in new nightly build
