### ISSUE TITLE
Toggle between cursive and non-cursive style not working

### ISSUE THREAD

**Issue by YummyHOF** [OpenPonk/openponk#106]
When checking or un-checking "Is Abstract" field on an entity, the name doesn't change styling.
Encountered on build [c0375c9](https://github.com/OpenPonk/plugins/commit/c0375c93b9357f12c44b31b8716ede83d7e05d67)

**Comment by YummyHOF** [comment]
After saving the `.opp` file, closing it and reopening it, the styling shows correctly.

**Comment by JanBliznicenko** [comment]
Hello, thank you for letting us know, it should be fixed in today's nightly build
