### ISSUE TITLE
Verify -> remove highlights not working

### ISSUE THREAD

**Issue by YummyHOF** [OpenPonk/openponk#109]
When I click on "remove highlight", no matter if something is highlighted or not, it produces an error
![image](https://github.com/OpenPonk/openponk/assets/140723524/17d643b0-23da-49ce-b5fd-5e0b1d55f138)

Removing highlights by clicking on "verify model", when the model is syntactly correct, works

**Comment by JanBliznicenko** [comment]
Hello, thank you for letting us know. It should be fixed in new nightly build (from 1 hour ago)
