### ISSUE TITLE
Anchors of relation with one entity on both ends misbehave

### ISSUE THREAD

**Issue by YummyHOF** [OpenPonk/openponk#110]
Steps to reproduce:
1. Create for example class in UML (or in OntoUML)
2. Create association with the class on both ends
3. Move anchors and/or add another anchors to reshape the association
4. Save to `opp` file and close
5. Reopen the file, step 3 should be nullified

Bonus:
1. Reopen the same file
2. Click on association to make it active
3. Try to add new anchor. Pharo should freeze.

**Comment by JanBliznicenko** [comment]
I like the bonus :D Will look into into

**Comment by JanBliznicenko** [comment]
Both should be fixed now
