### ISSUE TITLE
Error when opening UML opp file

### ISSUE THREAD

**Issue by YummyHOF** [OpenPonk/openponk#112]
I have OntoUML Diagram as follows:

![image](https://github.com/OpenPonk/openponk/assets/140723524/3f3ba8f4-cf96-46d2-a776-94eb9f8356a3)

And I convert it to UML and it produces following:

![image](https://github.com/OpenPonk/openponk/assets/140723524/15cc74f4-e3df-4422-a872-afa0d49903bb)

Then I save the file. Now, when I try to reopen the file it produces this error:

![image](https://github.com/OpenPonk/openponk/assets/140723524/9dad151b-8d8b-45b8-9d5e-0f3812cca793)

When I add names to the attributes in UML class Kind, error doesn't show up.

**Comment by JanBliznicenko** [comment]
Fixed by checking if name is not nil, then replacing by placeholder name. The nightly build with the fix is just being created and will be available in tens of minutes.
