### ISSUE TITLE
Unreachable attribute

### ISSUE THREAD

**Issue by YummyHOF** [OpenPonk/openponk#113]
1. Create UML class
2. Add some attributes to it
3. Delete a name of one attribute
4. Get left with an empty space, that can not be removed (can't be clicked):

![image](https://github.com/OpenPonk/openponk/assets/140723524/55cd9e33-5a00-42bb-a893-a4b4462fee36)

**Comment by JanBliznicenko** [comment]
Fixed by forcing placeholder name when if the name would be blank. The nightly build with the fix is just being created and will be available in tens of minutes.
