### ISSUE TITLE
Changes to diagram lost when switching models using tabs

### ISSUE THREAD

**Issue by jaburjak** [OpenPonk/openponk#116]
In a project with more than one model, switching between diagrams using tabs above the drawing area (highlighted in the screenshot below) causes changes made to the diagram to get lost.

![Screenshot_20240509_233434](https://github.com/OpenPonk/openponk/assets/4469124/6657d609-724e-44aa-9a45-806a930657c2)

Steps to reproduce:

1. Open a blank OntoUML or UML editor.
2. Place two classes in the model.
3. Create a new model in the same project.
4. Switch back to the first model using the tabs above the drawing area.
5. Move the classes to a different position in the diagram.
6. Double click on the first model in the left sidebar.

The classes in the diagram are back in their original positions. This does not happen when switching between models by double clicking on the model in the left sidebar.

The latest nightly (`8f65e2b`) is affected, previous releases were too.

**Comment by JanBliznicenko** [comment]
Hello and thank you for reporting the problem. It should be fixed now in master branch / current nightly build. In case the fix does not work, let me know.
