### ISSUE TITLE
RSAthensMorph>>resetShapeBeingDragged references missing variables and generates a walkback when moving connector lines

### ISSUE THREAD

**Issue by macta** [OpenPonk/openponk#117]
I noticed that when loading OpenPonk into P12 following the metacello instructions - that you get a walkback when moving connector lines as the method #resetShapeBeingDragged refs variables that don't exist anymore.
```
resetShapeBeingDragged

	eventBeginingDragging ifNil: [ ^ self ].
	self eventMouseDragStart: eventBeginingDragging
```

eventBeginingDragging is not an inst var anymore .

I think (not knowing this code) that something like the following is needed (which isn't quite right  though)

```
eventProcessor hasEvents ifTrue: [ 
	 eventProcessor eventMouseDragStart: HandMorph new asMouseMove ]
```
The HandMorph hack isn't right though - and there must be a better way

**Comment by JanBliznicenko** [comment]
You are right, the variable is no longer there. This is a change in Roassal, not Pharo. Library updates (like Roassal) were needed in order to move to Pharo 12. I will look into it.

**Comment by JanBliznicenko** [comment]
It should be fixed in current master branch / nightly build.

**Comment by macta** [comment]
yes this fixes it - strangely - reloading in the same image didn't pick up the new changes - the metacello cache doesn't detect a new version (you have to delete the iceberg directory and then it redownloads versions - which isn't ideal, but not a openponk issue). Thanks for the fix and will try out the app in P12

**Comment by JanBliznicenko** [comment]
> yes this fixes it - strangely - reloading in the same image didn't pick up the new changes - the metacello cache doesn't detect a new version (you have to delete the iceberg directory and then it redownloads versions - which isn't ideal, but not a openponk issue). Thanks for the fix and will try out the app in P12

Yes, it would only make the update if the "commitish" (name of branch / tag / commit number) actually changes, but once it keeps being "master", it does not do the update. If you only except one repository to be updated, you may do pull via Iceberg. But it might not always be the case, of course.
