### ISSUE TITLE
Showing hidden elements puts them all on the same position (0@0)

### ISSUE THREAD

**Issue by JanBliznicenko** [OpenPonk/openponk#18]
May be related to #14 (not saving positions of elements in diagrams)

**Comment by sdasda7777** [comment]
It also seems that after an element is hidden and shown, it is briefly (until selected) larger than before being hidden:

![image](https://user-images.githubusercontent.com/17746796/200073964-e6ac0bde-df71-4147-89c3-ee97be46bc48.png)

![image](https://user-images.githubusercontent.com/17746796/200074011-adb3c1a8-2211-4407-abeb-f1f2bc3acef7.png)

Curiously it appears as if the position of shown element were somehow based on camera or mouse position, as it is not static and not completely random either.

![image](https://user-images.githubusercontent.com/17746796/200074343-f37c0e34-1c72-47a3-a76a-0c9957e22771.png)

**Comment by JanBliznicenko** [comment]
It still does not remember original position, but at least does not stack them to the same position
