### ISSUE TITLE
How to add submodels to a project?

### ISSUE THREAD

**Issue by crunsk** [OpenPonk/openponk#29]
Hi,
(Edit 11.5.2020: 
The functionality I am searching for is displayed in this video at 2 minutes 3 seconds: https://youtu.be/_gQgXdJyr-0?t=124.
There a submodel is selected and you can open the submodel by pressing the green plus sign.)

I would to add submodels in BORM Editor. Either by using GUI or by coding.

For example how do you add the "Pizza Delivery" model to the other example project "Example Data Flows"?

Below is what I tried:

I tried to add  Pizza Delivery as submodel to Example Data Flows by adding project's diagram and model by code in the playground.
First I opened both projects in openponk-all-in-one.image and then i executed the following code:
```
projects := OPProject allInstances . 

project1 := projects at: 1.

project2 := projects at: 2.

project1models := project1 models.
project1model := project1models at: 1.

project1model project.

project1diagrams := project1 diagrams.
project1diagram := project1diagrams at: 1.

project2models := project2 models.
project2models add: project1model.
project2diagrams := project2 diagrams.
project2diagrams add: project1diagram.
```

That managed to get the Pizza Delivery model to become visible in the Submodel dropdown list. And when the submodel is selected a green plus sign appears in the block. But I am not yet able to open the submodel.

**Comment by crunsk** [comment]
One way to open the submodel is to inspect the node which contains the submodel and run command:
`self submodel open`.

I haven't yet figured out how to attach the submodel open command to the green plus icon or figure out why the button does not work.
The plus icon seems to be made visible in Class BormNodeFigure's method 'update':
```
update
	self show: plusIcon if: self model submodel isNotNil.
	super update
```

**Comment by crunsk** [comment]
Method createOwnedElements of BormNodeFigure creates puts insance of RTBitmat in plusIcon variable.

OPBormProcessNodeController's method renderFigureIn: seems to do the opening of the submodel. Here's the implementation of the method:

```
renderFigureIn: aView
	figure := self figureClass on: self model.
	figure renderIn: aView.
	figure plusIcon
		when: TRMouseLeftClick
		do: [ self diagramController editor workbench
				openEditorOn: self model submodel ].
	(self diagramController controllerForModel: self model owner)
		addedNodeFigure: figure.
	self diagramController figureAdded: figure.
	^ figure
```

**Comment by crunsk** [comment]
The submodel droplist is built in method buildEditorForm:

**Comment by JanBliznicenko** [comment]
Hello, thanks for all the feedback. The feature in the video has been working at the time of making the video, but unfortunately OpenPonk has changed in many ways since and this feature was not being used and therefore not even maintained. If you think you might be able to create the fix, doing that with pull request will be much appreaciated. Otherwise I will look at it. Cannot promise when, unfortunately, as we prioritize other features for now.

Jan

**Comment by crunsk** [comment]
Hi,
Thank you for the response. I will continue working on this at least periodically.

Is it ok if I add comments / notes to this issue as I try to fix this?

**Comment by JanBliznicenko** [comment]
Of course, I will be glad if you do :)

**Comment by crunsk** [comment]
Ok, good to hear :)

Text below contains some more of my notes about the problem.

The dropdown list for the submodels is created in method  "buildEditorForm:" of class "OPBormProcessNodeController".
And the list of submodels comes from message 'bormModels'.

**Comment by crunsk** [comment]
"
Steps for adding and being able to open a submodel.
1. create new borm or diagram project named 'Submodel_test'
2. add participant(name=usr) and state(name=start) for it
3. open pizza delivery example model 
4. Save objects to variables
"

```
projects := OPProject allInstances . 

project1 := projects at: 1. "pizza delivery"

project2 := projects at: 2. "Submodel_test"

project1models := project1 models.
project1model := project1models at: 1.

project1model project.

project1diagrams := project1 diagrams.
project1diagram := project1diagrams at: 1.

project2models := project2 models.
project2model := project2models at: 1.
project2diagrams := project2 diagrams.
project2diagram := project2diagrams at: 1.
```
"
5. add submodel to state 'start'"
```
project2Participant := project2model participants at: 1.
project2ParticipantState := project2Participant elements at: 1.
project2ParticipantState submodel: project1model.
```
"Try to open submodel, but it fails. I assume because of missing project diagram"

"6. Add pizza delivery diagram to project submodel_test"
`project2diagrams add: project1diagram.`
"Now opening submodel does not cause and error but it does not open the correct model. It seems to be that 'self projectController hasDiagram: arg1' returns true even though the projectcontroller does not have the arg1 diagram.

OPDiagram's method = compares `self asJson = arg1 asJson`. Because both submodel_test and pizza delivery are named default the program thinks they are the same. I'll change the name of pizzadelivery"
`project1diagram name: 'pizza'.`
"Another way how to tell the diagrams apart might be to change how asJson constructs the json object which is used to compare the objects.
Now comes notFound error. Because the pizza delivery diagram's name is not 'default'.
I'll remove the 'isDefault' test from method 'openEditorOn:'.
Now the submodel can be opened by pressing the '+' icon. 
I have more work to do. For example how to be able to select the submodel from dropdown list. Currently dropdown list shows only the model which is open."

**Comment by crunsk** [comment]
When more models to the submodel dorpdown list. You have to add the models to the project's variable 'models'. The next command is to be executed after commands in my previous message.
`project2 addModel: project1model.`
After running that command you should be able to select submodel 'Pizza Delivery' from Submodel dropdown list.

**Comment by crunsk** [comment]
I think the least amount of steps to be able to open the submodel is now:
1. Open openponk
2. Open the two example BORM projects
3. To view all models in the submodel dropdown list, change bormModels method to:
```
bormModels
|allModels|
allModels := OrderedCollection new.
	OPBormDiagramController allInstances do: [ :each | each editor workbench  projectController project models do: [ :each2 | allModels add: each2  ] ].
	^ allModels 
```
4. Select submodel from dropdown list
5. Try to open the submodel by pressing + icon
6. Add the submodels diagram to the project: `project diagrams add: (arg1 project diagrams at: 1)`
7. remove the isDefault test in `openEditorOn:`
8. rename the submodel's diagram
9. Open the submodel again or continue the execution after the error was raised

End result should be two models as tabs and the submodel should be the one that is open.

**Comment by crunsk** [comment]
I managed to add the functionality by changing to methods :

```
openEditorOn: arg1
| arg1Diagram  res |
 
arg1Diagram  := (arg1 project diagrams at: 1).
arg1Diagram name: arg1 name. "Change name of diagram to model's name"

res := project diagrams includes: arg1Diagram.
"Add diagram to the project if it's not yet added. Current projects which have been added to another project have only contained 1 diagram. That's why diagrams at: method has been used."
res ifFalse: [ project diagrams add: arg1Diagram. 
				   project models add: arg1.].
"Change the name of diagram so it will be differentiated from other diagrams in json comparison."

	self
		openEditorOnDiagram:
			(project diagrams
				detect: [ :arg2 | arg2 model = arg1 ])
```


```
bormModels
|allModels|
allModels := OrderedCollection new.
	OPBormDiagramController allInstances do: [ :each | each editor workbench  projectController project models do: [ :each2 | allModels add: each2  ] ].
	^ allModels 
```

**Comment by crunsk** [comment]
The bormModels method is in borm-editor repo: 
https://github.com/OpenPonk/borm-editor/blob/f27f446ac49878b0b2612bfcb69f1791c6be9b23/repository/OpenPonk-BormEditor/OPBormProcessNodeController.class.st#L20

And openEditorOn: method is in openponk: https://github.com/OpenPonk/openponk/blob/23826acb859f000436bc67bd20c9a92d64569eb4/repository/OpenPonk-Spec/OPWorkbench.class.st#L298

**Comment by JanBliznicenko** [comment]
It is not possible to have more models in a project and more diagrams of a single model. GUI around it is still not fully finished, but kinda usable. Thank you
