### ISSUE TITLE
Credentials in the project file?

### ISSUE THREAD

**Issue by Securitybits-io** [OpenPonk/openponk#36]
https://github.com/OpenPonk/openponk/blob/master/repository/OpenPonk-Telemetry/OPTelemetry.class.st

Looking at this file there are some credentials at the bottom, anything valid?

**Comment by peteruhnak** [comment]
Thanks for the report! This is sentry.io DSN (crash report endpoint), and isn't really a secret. The worst thing one can do with DSN is spam crash reports (which can't be helped), or data mine GitHub. :)

@JanBliznicenko this isn't used anymore, and iirc to use the latest sentry version (if you would want to setup everything again), you would need to make some changes in the pharo-sentry codebase and generate a new DSN.
