### ISSUE TITLE
'=' sign doesn't disappear after removing source/target default value in UML diagram association link

### ISSUE THREAD

**Issue by popovma1** [OpenPonk/openponk#55]
using the latest openponk-plugins-win-nightly.zip

writing default values works fine:

![img_before](https://user-images.githubusercontent.com/91681881/135483848-ff97d23e-ea25-43f7-81d4-7f5520f18ecd.png)

but after deleting default values '=' sign doesn't disappear:

![img_after](https://user-images.githubusercontent.com/91681881/135483853-5426ba8d-3c65-484e-8cb6-0ee115b14415.png)

**Comment by JanBliznicenko** [comment]
Thank you for report. Fixed in nightly build, to be released soon
