### ISSUE TITLE
Add SVG export feature

### ISSUE THREAD

**Issue by MarekSuchanek** [OpenPonk/openponk#57]
Diagrams should be possible to export as vector graphics... as it is basically just a few rectangles, lines and text.

PNG would be fine if image scaling is allowed; however, zoom does not affect PNG export. Then, when upscaled, it of course looks terrible. Also for editing purposes (such as changing class name to italics or emphasizing some class in a large model) would be SVG very useful.

**Comment by JanBliznicenko** [comment]
SVG is a little complicated, as svg paths need to be defined to some of our custom elements and general Roassal2 features that are not widely used (like background grid). However, I think I should be able to allow zoom of PNG export. I will take a look into that #58

**Comment by MarekSuchanek** [comment]
I will try to take a look at SVG how it could be done... I already did a bit of prototyping, I might submit a PR later on.

**Comment by JanBliznicenko** [comment]
There is a class RTSVGExporter that accepts instance of RTView, but it does not seem to work properly without any tweaks.

**Comment by MarekSuchanek** [comment]
Yeah.... I think it will be needed to implement custom version of RTSVGVisitor, and figure out how to transform the custom elements to SVG.

**Comment by JanBliznicenko** [comment]
I improved the RTSVGVisitor in a few ways so the SVG export kinda works. Currently in nightly build. It ignores font types, font sizes, text alignment, raster images (like in BORM participants) are not drawn and there might be more imperfections, but it exports at least something

**Comment by JanBliznicenko** [comment]
....aaand now it is broken again :)

**Comment by JanBliznicenko** [comment]
There is still room for improvements, but it is working enough :)
