### ISSUE TITLE
Custom association multiplicity gets lost from properties sidebar

### ISSUE THREAD

**Issue by jaburjak** [OpenPonk/openponk#59]
The latest nightly loses non-default multiplicities from the association properties sidebar, even though they are correctly displayed in the diagram:

![diagram](https://user-images.githubusercontent.com/4469124/140808505-e448709d-a351-409d-b7dc-2e03131dd85a.png)

![properties](https://user-images.githubusercontent.com/4469124/140808532-7e6d9991-8d21-4ca6-bae5-46f5f1e7d2a7.png)

Steps to reproduce:

1. Create association and overwrite multiplicity (for example to `2..*`) in the properties sidebar, confirm with Enter.
2. Multiplicity shown in the diagram and in the sidebar is `2..*`.
3. Click away from the association in the diagram, the properties sidebar becomes empty.
4. Click again on the association, the _Multiplicity_ field now has value `0..1`, even though the diagram still shows `2..*`.

The custom multiplicity is correctly shown in the diagram even after saving, closing and reopening the project, but is missing from the properties sidebar.

**Comment by JanBliznicenko** [comment]
Thank you for reporting the issue. Should be fixed now in nightly build. Numbered version will be released soon™
