### ISSUE TITLE
Transform to UML does not work

### ISSUE THREAD

**Issue by dvora141** [OpenPonk/openponk#60]
When trying to transform middle sized OntoUML model into UML Pharo freezes and just keeps demanding more and more RAM. I let it run till it had 8 GB of RAM and still did not get the desired result. I am using lates version (nightly build) currently available.
![UMLTransfrom](https://user-images.githubusercontent.com/57877509/140976319-3b57c768-428f-4561-adf3-2c7595935ec3.png)

**Comment by JanBliznicenko** [comment]
Hello, it seems there is an infinite recursion somewhere, or it might have been a temporary glitch. Does it happen every time you attempt to do the transformation or it happened just once?

**Comment by dvora141** [comment]
I tried it three times, even my friend attempted it with slightly older version and the issue still persists.

**Comment by JanBliznicenko** [comment]
Colleague did partial rework of transformation to UML. Could you, please, try doing the same thing current nightly build of OpenPonk?
If the issue still persist, please, upload here you .opp file with saved project that causes you issues.

**Comment by mstieranka** [comment]
I have the same issue on the current nightly build.

The .opp file can be found here: [uml_transform_issue.zip](https://github.com/OpenPonk/openponk/files/7540716/uml_transform_issue.zip)

**Comment by JanBliznicenko** [comment]
It was a problem of autolayouting not handling loops properly and should be now fixed. Feel free to try current nightly build (will be released in a few weeks).
