### ISSUE TITLE
Essential and inseparable modifiers are not saved

### ISSUE THREAD

**Issue by jaburjak** [OpenPonk/openponk#64]
On the latest nightly, associations lose the essential and inseparable modifiers when the project is saved and then reopened.

Steps to reproduce:

1. Create a new project with OntoUML diagram.
2. Create two Kinds with ComponentOf association between them.
3. Set the association as essential and inseparable.
4. Save the project as an `opp` file.
5. Close the project.
6. Reopen the project.
7. Association is no longer essential nor inseparable.

**Comment by JanBliznicenko** [comment]
Thank you for reporting. It should be fixed in current nightly build (actually, it is for a few months, I just forgot to close the issue :) ).
