### ISSUE TITLE
[Feature request] Make columns resizeable

### ISSUE THREAD

**Issue by sdasda7777** [OpenPonk/openponk#72]
I have encountered this unfortunate feature:
Columns of window here can't be resized, hiding the very valuable information. Even if there was not enough screen estate (which it clearly is here), it should probably be possible to resize beyond screen size and then move horizontally with a scrollbar.

![OpenPonk-Issue1](https://user-images.githubusercontent.com/17746796/194640844-a6800f64-3ae6-4e6c-9f0f-bfcff6422a79.png)

**Comment by JanBliznicenko** [comment]
Thank you a lot for all your feedback. Older version of the GUI framework had it enabled by default - current one does not, so I enabled it. The changed version will be built as a nightly build in several minutes.
