### ISSUE TITLE
[Bug] Note elements break model verification

### ISSUE THREAD

**Issue by sdasda7777** [OpenPonk/openponk#74]
Adding a Note element breaks model verification. To reproduce just add a Note element and run Diagram > Verify model.

![image](https://user-images.githubusercontent.com/17746796/194643478-7324cab1-5d1a-4f30-bde0-b7edca44280c.png)

![image](https://user-images.githubusercontent.com/17746796/194643153-c13d3c7d-71c4-416c-941c-0b5994ce4d6e.png)

**Comment by sdasda7777** [comment]
Okay, nevermind, this is actually only issue in the Stable version, works correctly in the nightly version.

**Comment by JanBliznicenko** [comment]
Yes, I should really produce a new version now - the current one is too old, I just did not consider the nightly one stable enough yet after updating GUI framework (difference of 5 years between old and new one) during summer.
