### ISSUE TITLE
[Bug] Mouse position detection when aligining arrows seems to be off

### ISSUE THREAD

**Issue by sdasda7777** [OpenPonk/openponk#75]
As you can see in the picture, even though the mouse was clicked when mouse was above the control point, the program thought it was outside and proceeded with selection.

![image](https://user-images.githubusercontent.com/17746796/194645246-2f89555e-73bf-4683-a85b-f3346ef62c8a.png)

![image](https://user-images.githubusercontent.com/17746796/194645135-3a8dab15-c64a-45da-98fa-5380d543212d.png)

**Comment by sdasda7777** [comment]
The screenshot above was taken in the Stable version. It seems to be much harder to do in the Nightly version, but still is possible:

![image](https://user-images.githubusercontent.com/17746796/194650269-6dd02045-9dd5-487b-b462-7975520b3233.png)

**Comment by JanBliznicenko** [comment]
True. There is actually black border around the black circle and the mouse handler only works for the main circle, not the border. I added a clickbox a little larger than the visible shape.
