### ISSUE TITLE
[Bug] Unable to "Export as PNG" to path that includes Unicode characters

### ISSUE THREAD

**Issue by sdasda7777** [OpenPonk/openponk#81]
This has baffled me for some time, but only today I have learned the export to PNG is actually supposed to be working.

After bit of testing, it seems that the functionality doesn't handle well paths that include Unicode characters. A message gets shown that export to given path was succesful, but nothing actually gets written.

Curiously, "Export as SVG" which I was using the whole time instead seems to work correctly.

**Comment by JanBliznicenko** [comment]
Huh, you're right, seems like nobody tried that yet. In my case, it did export, but looks like this :)

![obrazek](https://user-images.githubusercontent.com/9571633/200048748-53b7eb62-5856-4bf9-901f-007b9a761e6c.png)

**Comment by JanBliznicenko** [comment]
Forwarded the issue: https://github.com/ObjectProfile/Roassal3Exporters/issues/29

**Comment by JanBliznicenko** [comment]
It is no longer problem with new nightly build after moving to Pharo 11.
