### ISSUE TITLE
Guide on building and contributing?

### ISSUE THREAD

**Issue by sdasda7777** [OpenPonk/openponk#85]
I would love to contribute, but I have no idea where to start, which repos to clone, how to compile, how to name branches, what code style to use, stuff like that. Do you think you could improve on this?

**Comment by JanBliznicenko** [comment]
Hello, true, there is not much regarding that and I should make some guidelines, documentation about project structure etc. 
Are you familiar with Smalltalk / Pharo languages in any way?
You are a student of FIT, right? Could you write me on e-mail jan.bliznicenko (at) fit.cvut.cz or MS Teams?

**Comment by sdasda7777** [comment]
I made a pull request (#87) where I explained how to install cloned repository and how to commit any changes made to it.
