### ISSUE TITLE
bad gateway

### ISSUE THREAD

**Issue by Bazmundi** [OpenPonk/openponk#9]
Attempts to use download links from https://openponk.github.io/ result in BAD GATEWAY errors.

**Comment by peteruhnak** [comment]
Thanks for the report, the links should be fixed now.

Please note that OpenPonk development is currently dormant and should restart at the beginning of next year. Until then it is unlikely that any major fixes/issues can be addressed in any timely manner.

**Comment by Bazmundi** [comment]
Thanx. I will keep a log of issues, where I find them, for when the work
starts up again.

I am extremely interested in this approach as I was a keen metamodller in
DoME which was around 20 years ago, built on top of Smalltalk etc.
