### ISSUE TITLE
[Bug] Note element text is not shown immediately

### ISSUE THREAD

**Issue by sdasda7777** [OpenPonk/openponk#90]
I've noticed that when creating new Note element, the text only appears after clicking somewhere or moving the camera. Most likely there should be some update call happening right after creation and it isn't.

On the following picture, both elements have text, only for the second one it isn't shown yet.

![image](https://user-images.githubusercontent.com/17746796/214496939-604a980e-722f-48f4-8217-bc568a5f0e65.png)

**Comment by sdasda7777** [comment]
Manually calling renderFigureIn: after updating the text seems to fix it, but I'm not sure if it is the correct solution.

![image](https://user-images.githubusercontent.com/17746796/214506271-3f12063e-9a79-4afb-8076-41fd5cf321b0.png)

**Comment by JanBliznicenko** [comment]
Well, I actually do not like have anything figure-related in this method at all, but that is story for another day :)
For now, I think best solution would be to put `text signalUpdate` to the end of `OPResizableFigureWithText>>#updateText`. Sending `signalUpdate` to roassal element causes canvas to redraw and that is needed exactly when we update the text.

**Comment by sdasda7777** [comment]
That is definitely much more elegant, thanks!
