### ISSUE TITLE
[Feature request] Option to disable guidelines/gridlines

### ISSUE THREAD

**Issue by sdasda7777** [OpenPonk/openponk#95]
Is it possible to disable those gray guidelines/gridlines in OpenPonk? I can see it is a feature of the RTGridView and that it shows no gridlines  when gridSize is set to zero, but I don't think there is a simple way to do that in OpenPonk as a user. (I'm also not sure whether I should try to implement this because I'm not sure how much the GridView and this behaviour changes in Roassal 3)

I think such option, if implemented, would make the most sense in the bottom toolbar, at least that is where I would look for it personally. Probably on either side of zoom controls, to keep controls that aren't related to elements separate from those that are.

![image](https://user-images.githubusercontent.com/17746796/232888687-63eb5554-433d-4f3a-a29e-0a2e604025e3.png)

**Comment by JanBliznicenko** [comment]
All the grid stuff (visual grid lines, snapping to grid when dragging etc.) is actually one of 2 things not yet moved to Roassal3, as it will need to be reworked and I am not yet sure how many people actually use it (I know of exactly one at the moment). While I plan to reimplement it, it will take some time and I would like to have:
1) Option in OpenPonk settings to turn if on/off
2) Temporarily activate/deactive it when dragging with alt/shift/whatever pressed

**Comment by JanBliznicenko** [comment]
Feature completely removed in new nightly build (replaced by snapping dragged elements to other nearby elements)
