### ISSUE TITLE
[BUG] chyba BORM při přidávání data flow do diagramu

### ISSUE THREAD

**Issue by reakat** [OpenPonk/openponk#96]
Při přidání data flow do diagramu nelze přidat text a zobrazí se toto
![obrazek](https://github.com/OpenPonk/openponk/assets/56316045/7d364fce-0db8-49db-b3ba-d1ea949e140c)

**Comment by JanBliznicenko** [comment]
Dobrý den, mělo by být opraveno v novém nightly buildu (a po čase v OpenPonku 4.0 :) )
